const Languages = {
    common: {
        cancel: 'Hủy',
        ok: 'Chọn',
        back: 'Quay lại',
        yes: 'Có',
        no: 'Không',
        close: 'Đóng',
        search: 'Tìm kiếm',
        agree: 'Đồng ý',
        or: 'Hoặc',
        continue: 'Tiếp tục',
        currency: 'VND',
        percent: '%',
        tienNgayVn: 'TienNgay',
        sdtIfErrAccess: '10991008',
        vn: '.vn',
        email: 'Email',
        name: 'Tên người dùng',
        sdt: 'Số điện thoại',
        cmt: 'Số CMT/Căn cước công dân',
        inputEmail: 'Nhập Email',
        inputName: 'Nhập tên người dùng',
        inputPhone: 'Nhập số điện thoại',
        phoneNumber: 'Số điện thoại',
        inputCMT: 'Nhập số',
        updateUser: 'Chỉnh sửa User',
        deleteUser: 'Xoá User',
        position: 'Chức vụ',
        inputPosition: 'Chọn chức vụ',
        callPhone: 'Gọi điện thoại',
        historyCall: 'Lịch sử cuộc gọi',
        notification: 'Thông báo',
        showAllNotify: 'Xem tất cả thông báo',
        mustChoose: '*',
        input: 'Nhập',
        add: 'Thêm'
    },
    errorMsg: {
        noInternet: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        sessionExpired: 'Kết nối bị gián đoạn, vui lòng thử lại!',
        positionRequired: 'Thông tin phân quyền chức vụ không được để trống',
        userNameRequired: 'Họ và tên không được để trống',
        userInfoLength: 'Thông tin không được để trống',
        imageRequired: 'Hình ảnh không được để trống',
        userInfoRegex: 'Không được chứa ký tự đặc biệt hoặc chữ',
        userNameLength: 'Họ và tên không được ít hơn 8 ký tự',
        userNameRegex: 'Không được chứa ký tự đặc biệt hoặc số',
        errIllegal: 'Mật khẩu không hợp lệ',
        nameRequired: 'Tên không được để trống',
        emailNull: 'Email không được để trống',
        emailRegex: 'Email không đúng định dạng',
        cardNull: 'Số CMND/CCCD không được để trống',
        cardRegex: 'Số CMND/CCCD phải là số',
        cardCheck: 'Số CMND/CCCD không hợp lệ',
        pwdNull: 'Mật khẩu không được để trống',
        pwdCheck: 'Mật khẩu không được ít hơn 8 ký tự',
        conFirmPwd: 'Xác nhận mật khẩu không trùng khớp với mật khẩu',
        emptyAmount: 'Bạn chưa nhập số tiền',
        minAmount: 'Số tiền nạp/rút tối thiểu là 100.000 vnđ',
        phoneIsEmpty: 'Số điện thoại không được để trống',
        phoneRegex: 'Số điện thoại không đúng định dạng',
        phoneCount: 'Số điện thoại chỉ được 10 số',
        taxIdEmpty: 'Mã số thuế không được để trống',
        taxIdSyntax: 'Mã số thuế không được ít hơn 10 ký tự',
        specialCharacters: 'Không được chứa kí tự đặc biệt',
        birthdayEmpty: 'Ngày sinh ',
        birthdayNotNumber: 'Ngày sinh không đúng định dạng ví dụ: 1970-01-01',
        birthdayAge18: 'Chưa đủ 18 tuổi',
        birthdayAge95: 'Vượt quá 95 tuổi',
        errProvince: 'Thành phố không được bỏ trống',
        errDistrict: 'Quận huyện không được bỏ trống',
        errWard: 'Xã phường không được bỏ trống',
        errFunds: 'Nguồn tiền không được bỏ trống',
        errMoveto: 'Chuyển tới không được bỏ trống',
        errKeyBook: 'Mã sổ không được bỏ trống',
        errMsgOldPwdCompare: 'Mật khẩu cũ bạn nhập không đúng',
        errMsgCurrentPwdCompare: 'Mật khẩu nhập lại không trùng khớp',
        errMsgEmpty: 'Mật khẩu nhập không được để trống',
        errMsgLength: 'Mật khẩu nhập phải từ 8 kí tự trở lên',
        errMsgSpecialChar: 'Mật khẩu nhập không được chứa kí tự đặc biệt',
        errMsgSpaceChar: 'Mật khẩu nhập không được chứa kí tự trống',
        errMsgUpperChar: 'Mật khẩu phải có 1 kí tự in hoa',
        errMsgGender: 'Giới tính không được bỏ trống',
        genderRequired: 'Giới tính không được để trống'
    },
    header: {
        textCenter: 'HƯỚNG DẪN SỬ DỤNG CHỨC NĂNG CƠ CẤU, GIA HẠN',
        textCenter1: 'HƯỚNG DẪN SỬ DỤNG BẢO HIỂM',
        name: '',
        personalInformation: 'Thông tin cá nhân',
        setting: 'Cài đặt tài khoản',
        logout: 'Đăng xuất'
    },
    footer: {
        copyRight: 'Bản quyền © 2019 - 2022 Công ty Cổ phần Công nghệ Tài chính Việt',
        contactAccessIfErr: 'Hotline: '
    },
    menu: {
        salesInfo: '1. Quản lý thông tin bán hàng',
        contract: '2. Quản lý hợp đồng',
        insurance: '3. Quản lý bảo hiểm',
        insuranceOutOfSale: '3.1 Quản lý bảo hiểm bán ngoài',
        payment: '4. Thanh toán',
        other: '5. Khác',
        calculateTool: '6. Tool tính toán',
        menu: 'Menu'
    },
    login: {
        login: 'Đăng nhập'
    },
    home: {
    },
    contract: {
        createSuccess: 'Tạo hợp đồng thành công',
        descriptionCreate: 'Hợp đồng cửa bạn sẽ được tạo với trạng thái mới',
        confirmCreate: 'Xác nhận tạo mới hợp đồng',
        searchInfo: 'Tìm kiếm thông tin',
        steps: {
            customerInformation: 'Thông tin khách hàng',
            loanInfo: 'Thông tin khoản vay',
            disbursementInformation: 'Thông tin giải ngân',
            appraisalInformation: 'Thông tin thẩm định'
        },
        createLoanContract: ' Tạo mới hợp đồng vay',
        CustomerInformation: 'Thông tin khách hàng',
        AnewCustomer: 'Khách hàng mới ',
        OldCustomers: 'Khách hàng cũ',
        cmt: 'So sánh CMTND và chân dung',
        uploadImg: 'Hướng dẫn upload ảnh nhanh',
        beforeID: 'Mặt trước chứng minh nhân dân',
        label: '<span>Thả</span> Hình ảnh vào đây hoặc <span>click</span> để tải lên',
        labels: ['Thả', 'hình ảnh vào đây hoặc', 'click ', 'để tải lên'],
        textLabel: 'CMND cũ, CMND mới, Căn cước công dân, Hộ chiếu',
        afterID: 'Mặt sau CMND',
        portrait: 'Ảnh chân dung',
        reselect: 'Chọn lại',
        identification: 'Nhận dạng',
        customerName: 'Tên khách hàng',
        dateOfBirth: 'Ngày sinh',
        telephoneNumber: 'Số điện thoại',
        kindsOfPapers: 'Các loại giấy tờ',
        relatedContract: 'Hợp đồng liên quan',
        numberID: 'Số CMND/CCCD hiện tại',
        dateRange: 'Ngày cấp',
        IssuedBy: 'Nơi cấp',
        numberIdOld: 'Số CMND/CCCD cũ',
        email: 'Email',
        married: 'Đã kết hôn',
        notMarried: 'Chưa kết hôn',
        divorce: 'Ly hôn',
        maritalStatus: 'Tình trạng hôn nhân',
        sex: 'Giới tính',
        customerResources: 'Nguồn khách hàng',
        star: '<span> * </span>',
        householdAddress: 'Địa chỉ hộ khẩu',
        city: 'Tỉnh/Thành phố',
        choose: 'Chọn',
        district: 'Quận/Huyện',
        ward: 'Phường/Xã',
        village: 'Thôn/Xóm/Tổ',
        addressIsIn: 'Địa chỉ đang ở',
        residenceForm: 'Hình thức cư trú',
        resident: 'Thường trú',
        companyAddress: 'Địa chỉ công ty',
        import: 'Nhập',
        companyPhoneNumber: 'Số điện thoại công ty ',
        importTelephoneNumber: 'Nhập số điện thoại',
        position: 'Vị trí, Chức vụ',
        job: 'Nghề nghiệp',
        timeLive: 'Thời gian sinh sống',
        jobInformation: 'Thông tin việc làm',
        nameCompany: 'Tên công ty ',
        workingTime: 'Thời gian làm việc tại công ty ',
        income: 'Thu nhập',
        fromTakeWage: ' Hình thức nhận lương ',
        relativeInformation: 'Thông tin người thân',
        referencePerson1: 'Người tham chiếu 1',
        referencePerson2: 'Người tham chiếu 2',
        referencePerson3: 'Người tham chiếu 3',
        chooseRelationship: 'Chọn mối quan hệ ',
        residentialAddress: ' Địa chỉ cư trú ',
        feedback: 'Phản hồi',
        referencePurposes: 'Mục đích tham chiếu ',
        address: 'Địa chỉ',
        seeRelatedContract: 'Xem hợp đồng liên quan',
        text: 'text',
        number: 'number',
        date: 'date',
        importId: 'Nhập Số CMND/ CCCD',
        man: 'Nam',
        girl: 'Nữ',
        next: 'Tiếp tục',
        keys: [
            'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'fifteen'
        ],
        formality: 'Hình thức',
        save: 'Lưu lại',
        back: 'Quay lại',
        bank: 'Ngân hàng',
        transaction: 'Phòng giao dịch',
        branch: 'Chi nhánh',
        accountHolder: 'Chủ tài khoản',
        cardName: 'Tên chủ thẻ ATM',
        cardNumber: 'Số thẻ ATM',
        accountNumber: 'Số tài khoản',
        contractList: 'Danh sách hợp đồng',
        contractDetail: 'Chi tiết hợp đồng',
        createContract: 'Tạo hợp đồng',
        seeLicense: 'Xem chứng từ',
        tabs: {
            allContract: 'Tất cả hợp đồng',
            borrowing: 'Đang vay',
            paymentOverdue: 'Quá hạn thanh toán',
            paymentSettlement: 'Quá hạn tất toán'
        },
        tableExpertise: {
            loanOrganizationName: 'Tên tổ chức vay',
            remainingBalance: 'Dư nợ còn lại',
            completed: 'Đã tất toán',
            installmentPayment: 'Tiền phải trả hàng kỳ',
            outOfDate: 'Quá hạn',
            placeholderLoanOrganizationName: 'Chọn tên tổ chức vay',
            placeholderRemainingBalance: 'Nhập dư nợ còn lại',
            placeholderCompleted: 'Nhập số tiền đã tất toán',
            placeholderInstallmentPayment: 'Nhập chức năng',
            placeholderOutOfDate: 'Nhập quá hạn'
        },
        table: {
            stt: 'STT',
            position: 'Chức năng',
            type: 'Loại hợp đồng',
            contractCode: 'Mã hợp đồng',
            couponCode: 'Mã phiếu ghi',
            customerName: 'Khách hàng',
            customerPhone: 'Số điện thoại',
            customerCccd: 'CMND/CCCD/Hộ chiếu',
            property: 'Tài sản',
            loan: 'Số tiền vay',
            status: 'Trạng thái',
            formOfInterestPayment: 'Hình thức đóng lãi',
            time: 'Thời gian',
            transaction: 'Phòng giao dịch',
            creator: 'Người tạo',
            dateCreated: 'Ngày tạo',
            disbursementDate: 'Ngày giải ngân'
        },
        tableLoan: {
            paymentPeriod: 'Kỳ trả',
            dateOfMaturity: 'Ngày đến hạn',
            numberDay: 'Số ngày',
            numberLatePaymentDate: 'Số ngày chậm trả',
            moneyPayableMonthly: 'Tiền phải trả hàng kì',
            initialMoney: 'Tiền gốc',
            profitMoney: 'Tiền lãi',
            managementStorage: 'Phí tư vấn quản lý & thẩm định lưu trữ tài sản',
            totalPayment: 'Tổng tiền thanh toán',
            paid: 'Đã thanh toán',
            unpaid: 'Còn lại chưa trả',
            status: 'Tình trạng',
            forfeit: 'Phạt chậm trả'
        },
        advancedSearch: 'Tìm kiếm nâng cao',
        excel: 'Xuất excel',
        placeHolderSearch: 'Nhập mã hợp đồng, mã phiếu thu, CCCD, tên khách hàng, số điện thoại',
        descriptionModal: 'Tìm kiếm hợp đồng',
        modalSearch: {
            transaction: 'Phòng giao dịch',
            propertyType: 'Loại tài sản',
            propertyName: 'Tên tài sản',
            time: 'Thời gian',
            activeStatus: 'Trạng thái hoạt động',
            contractType: 'Loại hợp đồng',
            loanForm: 'Hình thức vay',
            placeholderTransaction: 'Chọn phòng giao dịch',
            placeholderPropertyType: 'Chọn loại tài sản',
            placeholderPropertyName: 'Nhập tên tài sản',
            placeholderTime: 'Chọn thời gian',
            placeholderActiveStatus: 'Chọn trạng thái hoạt động',
            placeholderContractType: 'Chọn loại hợp đồng',
            placeholderLoanForm: 'Chọn hình thức vay',
            fromDate: 'Từ ngày',
            toDate: 'Đến ngày'
        },
        fileAppraisal: 'Thẩm định hồ sơ',
        fieldAppraisal: 'Thẩm định thực địa',
        creditRelationshipInformation: 'Thông tin quan hệ tín dụng',
        add: 'Thêm mới',
        placeholderInfo: 'Nhập thông tin',
        addCreditRelationshipInformation: 'Thêm thông tin quan hệ tín dụng',
        exception: 'Ngoại lệ hồ sơ',
        addException: 'Thêm ngoại lệ hồ sơ',
        typeofDocument: 'Chọn loại giấy tờ ',
        livingInHousehold: 'Đang sống tại hộ khẩu',
        loanRecoveryDetails: 'Chi tiết thu hồi khoản vay',
        noticeUpload: 'CMND cũ, CMND mới, Căn cước công dân, Hộ chiếu (Ảnh có định dạng "jpeg", "png", "jpg", <span>dung lượng < 2MB</span>)',
        clearUser: 'Xoá User',
        debitBalanceInformation: 'Thông tin dư nợ',
        loanProducts: 'sản phẩm vay',
        paymentMethod: 'Hình thức trả',
        seeActualFees: 'Xem phí thực tính',
        viewCode: 'Xem mã BH KV',
        paymentPeriodDetails: 'Chi tiết kì thanh toán',
        pay: 'Thanh toán',
        settlement: 'Tất toán',
        impactHistory: 'Lịch sử tác động',
        uploadWaiverForm: 'Upload đơn miễn giảm',
        paymentPeriod: 'Kỳ thanh toán',
        paymentHistory: 'Lịch sử trả nợ',
        tablePaymentHistory: {
            stt: 'STT',
            code: 'Mã phiếu thu',
            dateCreated: 'Ngày tạo',
            dateOfPayment: 'Ngày thanh toán',
            paymentAmount: 'Số tiền thanh toán',
            amountExemption: 'Số tiền miễn giảm',
            overdueFee: 'Phí quá hạn',
            overdueDate: 'Ngày quá hạn',
            renewalFee: 'Phí gia hạn',
            extraMoney: 'Tiền thừa',
            updater: 'Người cập nhật',
            paymentType: 'Loại thanh toán',
            status: 'trạng thái',
            notePGD: 'Ghi chú PGD',
            accountingNotes: 'Ghi chú kế toán',
            impactHistory: 'Lịch sử tác động'
        },
        tableImpactHistory: {
            stt: 'STT',
            time: 'Thời gian',
            performer: 'Người thực hiện',
            result: 'Kết quả',
            paymentAppointmentDate: 'Ngày hẹn thanh toán',
            amountPaymentAppointment: 'Số tiền hẹn thanh toán',
            note: 'Ghi chú'
        },
        errorUpload: 'Ảnh bị lỗi vui lòng xem lại hướng dẫn upload ảnh',
        cancel: 'Huỷ chọn',
        payerName: 'Tên người thanh toán',
        relationshipWithOwner: 'Quan hệ với chủ hợp đồng',
        payerPhone: 'Số điện thoại người thanh toán',
        realityDate: 'Ngày thực tế',
        datePayment: 'Ngày khác hàng thanh toán',
        numberDaysDifference: 'Số ngày chênh lệch thực tế và thanh toán',
        deductionFee: 'Phí khấu trừ',
        totalAmountDeductionFee: 'Tổng tiền khẩu trừ',
        form: 'Hình thức',
        feeDeduction: 'Phí giảm trừ',
        totalAmountDue: 'Tổng tiền đến kỳ phải trả',
        moneyPayDate: 'Tiền đến ngày Thanh toán',
        actualDifferenceAndPayout: 'Tiền chênh lệch thực tế và thanh toán',
        totalAmountMinus: 'Tổng tiền khẩu trừ',
        penaltyForLatePayment: 'Tiền phạt chậm trả',
        overdueMoney: 'Tiền quá hạn',
        method: 'Phương thức',
        validMoney: 'Tiền thanh toán hợp lệ ',
        moneyPaidByCustomer: 'Tiền khách hàng thanh toán',
        collectedContent: 'Nội dung thu',
        addCollectedContent: 'Thêm nội dung thu tiền',
        confirmPay: 'Xác nhận thanh toán',
        actualSettlementSate: 'Tông tiền tất toán ngày thực tế',
        totalAmountSettlement: 'Tổng tiền đến ngày tất toán',
        earlySettlementFee: 'Phí tất toán trước hạn',
        fee: 'Tiền phí',
        interest: 'Tiền lãi',
        exemptionType: 'Loại miễn giảm',
        confirmEmailCEO: 'Xác nhận của CEO qua email',
        applicationExemption: 'Đơn miễn giảm (bản giấy)',
        contractSuggest: 'Hợp đồng đề nghị',
        moneyRequestedReduced: 'Số tiền KH đề nghị miễn giảm',
        suggestedDate: 'Ngày đề nghị',
        noteDate: 'Chọn từ "Ngày đến hạn" của kỳ còn nợ gần ngày giải ngân nhất, đến hết kỳ còn nợ đó',
        dateOfApplicationSigning: 'Ngày khách hàng ký đơn miễn giảm',
        uploadImage: 'Đăng tải hình ảnh',
        note: 'Ghi chú/Note',
        sendForm: 'Gửi yêu cầu miễn giảm',
        addImage: 'Thêm hình ảnh',
        remainingPrincipalBalance: 'Dư nợ gốc còn lại',
        amountPaid: 'Số tiền cần trả',
        moneyPaid: 'Tiền đã trả',
        moneyOwed: 'Tiền còn nợ',
        slowPeriod: 'Số kỳ chậm trả',
        unpaidMoney: 'Tiền chưa trả'
    },
    seeLicense:{
        loadDocument: 'Tải ảnh xuống',
        download: 'Tải xuống',
        profileFamily: 'Hồ sơ nhân thân',
        detailImage: 'Chi tiết hình ảnh',
        detailVideo: 'Chi tiết video',
        unSupportVideo: 'Trình duyệt không hỗ trợ đuôi file có dạng .'
    },
    popup: {
        title: 'Thông báo popup',
        description: 'Đây là nội dung thông báo'
    },
    userManagement: {
        userManagement: 'Quản lý User',
        newUser: 'Tạo mới User',
        groupUser: 'Nhóm quyền',
        table: {
            stt: 'STT',
            email: 'Email',
            name: 'Tên',
            sdt: 'Số điện thoại',
            date: 'Ngày tạo',
            status: 'Trạng thái',
            position: 'Chức năng',
            detail: 'Xem chi tiết'
        },
        paginationStart: 'Hiện thị từ 1 đến 10 trong số',
        paginationEnd: 'bản ghi',
        search: 'Tìm kiếm',
        searchUser: 'Tìm kiếm User',
        modal: {
            email: 'Email',
            name: 'Tên người dùng',
            phone: 'Số điện thoại',
            position: 'Chức năng',
            inputEmail: 'Nhập Email',
            inputName: 'Nhập tên người dùng',
            inputSdt: 'Nhập số điện thoại',
            inputPosition: 'Nhập chức năng',
            status: 'Chọn trạng thái'
        },
        createUser: 'Tạo mới User'
    },
    formUser: {
        user: 'User',
        content: 'sẽ không còn phân quyền này sau khi xoá phân quyền',
        personalInformation: 'Thông tin cá nhân user',
        authorizationInformation: 'Thông tin phân quyền',
        importEmail: 'Nhập email',
        email: 'Email',
        importUser: 'Nhập tên người dùng',
        userName: 'Nhập tên người dùng',
        importPhone: 'Nhập số điện thoại',
        telephone: 'Số điện thoại',
        identityCard: 'Số chứng minh thư / căn cước công dân',
        importNumber: 'Nhập số ',
        btnSave: 'Lưu tài khoản',
        cancel: 'Hủy',
        donationGroup: 'Nhóm quyền',
        search: 'Tìm kiếm',
        save: 'Lưu tài khoản',
        saveUpdate: 'Lưu chỉnh sửa',
        createUser: 'Tạo mới User',
        userDetails: ' Chi tiết user',
        addPermissions: 'Thêm phân quyền',
        transaction: 'Phòng giao dịch',
        listPosition: 'Danh sách chức vụ',
        removePermissions: 'Xoá phân quyền',
        contentDeletePosition: 'User linhltt@tienngay.vn sẽ không còn chức vụ này và các phân quyền đi kèm sau khi xoá chức vụ',
        positionHint: 'Chọn chức vụ',
        star: ' *',
        updateUser: 'Chỉnh sửa User',
        deleteUser: 'Xoá User',
        userManagementDetail: 'Thông tin chi tiết'
    },
    positionManagement: {
        positionManagement: 'Quản lý chức vụ',
        decentralizedManagement: 'Quản lý phân quyền',
        addDecentralized: 'Thêm phân quyền',
        position: 'Chức vụ',
        nameDecentralized: 'Tên phân quyền',
        depict: 'Mô tả',
        status: 'Trạng thái',
        search: 'Tìm kiếm',
        createPosition: 'Tạo mới chức vụ',
        updatePosition: 'Chỉnh sửa chức vụ',
        namePosition: 'Tên chức vụ',
        manager: 'Thuộc quản lý',
        inputNamePosition: 'Nhập tên chức vụ',
        chooseManager: 'Chọn quản lý',
        save: 'Lưu chức vụ',
        saveEdit: 'Lưu chỉnh sửa',
        informationPosition: 'Thông tin phân quyền chức vụ',
        infoPosition: 'Thông tin chức vụ',
        editPosition: 'Chỉnh sửa chức vụ',
        listPosition: 'Danh sách phân quyền',
        noManage: 'Không quản lý',
        manageOnlyOneRoom: 'Quản lý chỉ một phòng',
        manageMultipleRoom: 'Quản lý nhiều phòng'
    },
    loanInfo: {
        loanInfo: 'Thông tin khoản vay',
        vehicleSignUpInfo: 'Thông tin đăng ký xe',
        insuranceInfo: 'Bảo hiểm',
        loanFormat: ' Hình thức vay',
        typeAsset: 'Loại tài sản',
        loanProduct: 'Sản phẩm vay',
        assetName: 'Tên tài sản',
        propertyValue: 'Giá trị tài sản',
        maxLoanAmount: 'Số tiền tối đa có thể vay',
        depreciation: 'Khấu hao tài sản',
        loanPurpose: 'Mục đích vay',
        loanAmount: 'Số tiền vay',
        loanTimer: 'Thời gian vay',
        formInterestPayment: 'Hình thức trả lãi',
        specialOffer: 'Chương trình ưu đãi',
        frontVehicleCard: 'Mặt trước ĐKX',
        behindVehicleCard: 'Mặt sau ĐKX',
        imgLocate: 'Ảnh định vị',
        assetInformation: 'Thông tin tài sản',
        vnd: 'Vnđ'
    }


};


export default Languages;
